### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by s-c-wang** [mimiliaogo/cambridge-dictionary-crawler#1]
Hello, I am fairly new to GitHub and just made a vocabulary-memorizing Python program a while ago. The thing is I knew little about copyrights and license, and used some of the codes of this repository in my code. Is it possible that you make this repository withan MIT license? Thank you in advance!

For some reason I cannot make my repo private, I will keep trying. [Here's the link](https://github.com/excusezmoi/memorizingVocabularyUsingForgettingCurve)

**Comment by mimiliaogo** [comment]
I add an MIT license to this repo for your request.
